added readme file
ArastoSahbaei/codic-education-server pull request #22
Opened 2021-09-23 06:33 UTC by ItsSteph

first draft for README.md - let me know if something is missing or needs to change.

2021-09-23 15:54 UTC, ArastoSahbaei requested changes

2021-09-23 15:54 UTC, ArastoSahbaei commented on README.md
> +Insomnia - https://insomnia.rest/download
**Node.js**

Insomnia är inte ett requirement, men definitivt en recommendation.

2021-09-23 15:54 UTC, ArastoSahbaei commented on README.md
> +    ENVIROMENT = DEVELOPMENT
Du kan addera alla andra dolda variabler vi har (men visa inte värdet)

```
DEV_DATABASE_URL = mongodb://localhost/codic
PROD_DATABASE_URL = TBD
PORT = 3001
ENVIROMENT = DEVELOPMENT

EMAIL = x
CLIENT_ID = x
CLIENT_SECRET = x
REFRESH_TOKEN = x

PAYPAL_CLIENT_ID = x
PAYPAL_CLIENT_SECRET = x 
```

2021-09-23 15:54 UTC, ArastoSahbaei commented on README.md
> +npm start
_nodemon Server.js_

2021-09-23 15:54 UTC, ArastoSahbaei commented on README.md
> +Do not push to master! Always create a new branch that you can commit and push to.
master är låst nu så det går inte att pusha till master :)!
Du kan byta ut det stycket . '_Do not push to master!_'
master is the main branch, but is locked during development. (exempelvis)

2021-09-23 15:54 UTC, ArastoSahbaei commented on README.md
> +7. Now you should be able to see the Codic database in your menu
ta bort Codic. räcker med:
Now you should be able to see the database in your menu

2021-09-24 06:46 UTC, ItsSteph commented on README.md
> +    ENVIROMENT = DEVELOPMENT
DEV_DATABASE_URL = mongodb://localhost/codic + ENVIROMENT = DEVELOPMENT behövs för att kunna köra projektet då .env filen inte är med när man hämtar projektet från git. Ska alla dolda variabler finns med i .env filen?

2021-09-24 12:26 UTC, ItsSteph commented on README.md
> +    ENVIROMENT = DEVELOPMENT
@ArastoSahbaei  ville du ha med variablerna såhär? Dev url och Enviroment måste vara synlig annars vill min dator inte köra servern. Men dom andra behöver inte vara med för att man ska kunna starta servern

2021-09-24 12:52 UTC, merged